sonar.projectKey=S-GOST_BACKEND
sonar.projectName=BACKEND
sonar.organization=s-gost
sonar.host.url=https://sonarcloud.io
sonar.sources=controllers,models,routes,utils
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml
